// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer an unpooled connection for migrations, but allow environments
    // such as Vercel to build when only DATABASE_URL is configured.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
